[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$OutputEncoding = [System.Text.Encoding]::UTF8
$ErrorActionPreference = "SilentlyContinue"

Write-Host "Generating AI review pack..."

$scriptDir = if ($PSScriptRoot) {
    $PSScriptRoot
} else {
    Split-Path -Parent $MyInvocation.MyCommand.Path
}

$reportDir = Join-Path $scriptDir "ScriptReports"
$aiReportDir = Join-Path $scriptDir "AIReports"

if (!(Test-Path $reportDir)) {
    Write-Host "ScriptReports folder not found."
    exit
}

if (!(Test-Path $aiReportDir)) {
    New-Item -ItemType Directory -Path $aiReportDir | Out-Null
}

$fileTimestamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
$output = Join-Path $aiReportDir "ai_review_prompt_$fileTimestamp.txt"

function Convert-HtmlToPlainText($html) {
    if ([string]::IsNullOrWhiteSpace($html)) {
        return ""
    }

    $text = $html
    $text = [regex]::Replace($text, "<style[\s\S]*?</style>", "")
    $text = [regex]::Replace($text, "<script[\s\S]*?</script>", "")
    $text = [regex]::Replace($text, "<[^>]+>", " ")
    $text = [System.Net.WebUtility]::HtmlDecode($text)
    $text = [regex]::Replace($text, "\s{2,}", " ")
    return $text.Trim()
}

function Mask-IPv4Value($ip) {
    $parts = $ip.Split(".")

    if ($parts.Count -ne 4) {
        return $ip
    }

    $a = [int]($parts[0])
    $b = [int]($parts[1])
    $c = [int]($parts[2])

    if ($ip -eq "127.0.0.1") {
        return $ip
    }

    if ($ip -eq "0.0.0.0") {
        return $ip
    }

    if ($a -eq 192 -and $b -eq 168) {
        return "$a.$b.$c.x"
    }

    if ($a -eq 10) {
        return "$a.$b.$c.x"
    }

    if ($a -eq 172 -and $b -ge 16 -and $b -le 31) {
        return "$a.$b.$c.x"
    }

    if ($a -eq 169 -and $b -eq 254) {
        return "$a.$b.x.x"
    }

    return "<PUBLIC_IP>"
}

function Sanitize-ReportText($text) {
    if ([string]::IsNullOrWhiteSpace($text)) {
        return $text
    }

    $currentUser = $env:USERNAME
    $computerName = $env:COMPUTERNAME

    if (![string]::IsNullOrWhiteSpace($currentUser)) {
        $text = $text.Replace($currentUser, "<USER>")
    }

    if (![string]::IsNullOrWhiteSpace($computerName)) {
        $text = $text.Replace($computerName, "<COMPUTER>")
    }

    # User directory paths
    $text = [regex]::Replace($text, 'C:\\Users\\[^\\\s"]+', 'C:\Users\<USER>')

    # Windows user SID
    $text = [regex]::Replace($text, 'S-1-5-21-\d+-\d+-\d+-\d+', '<USER_SID>')

    # MAC addresses
    $text = [regex]::Replace($text, '\b(?:[0-9A-Fa-f]{2}[:-]){5}[0-9A-Fa-f]{2}\b', '<MAC_REDACTED>')

    # BSSID line
    $text = [regex]::Replace($text, '(?i)(BSSID\s*:\s*)(.+)', '$1<MAC_REDACTED>')

    # SSID / Wi-Fi profile
    $text = [regex]::Replace($text, '(?i)(SSID\s*:\s*)(.+)', '$1<SSID_REDACTED>')
    $text = [regex]::Replace($text, '(?i)(Profile\s*:\s*)(.+)', '$1<SSID_REDACTED>')

    # IPv6 addresses
    $text = [regex]::Replace($text, '\b(?:[0-9A-Fa-f]{0,4}:){2,}[0-9A-Fa-f]{0,4}\b', '<IPV6_REDACTED>')

    # IPv4 addresses, conservative compatible version
    $ipv4Matches = [regex]::Matches($text, '\b(?:\d{1,3}\.){3}\d{1,3}\b')

    $uniqueIPs = @()

    foreach ($m in $ipv4Matches) {
        if ($uniqueIPs -notcontains $m.Value) {
            $uniqueIPs += $m.Value
        }
    }

    foreach ($ip in $uniqueIPs) {
        $masked = Mask-IPv4Value $ip
        $text = $text.Replace($ip, $masked)
    }

    # Public IP field fallback
    $text = [regex]::Replace($text, '(?i)(Public IP\s+)(\S+)', '$1<PUBLIC_IP>')

    return $text
}

function Get-LatestReportText($pattern, $title) {
    $file = Get-ChildItem -Path $reportDir -Filter $pattern -File |
        Sort-Object LastWriteTime -Descending |
        Select-Object -First 1

    if ($null -eq $file) {
        return "===== $title =====`nNo report found.`n"
    }

    $html = Get-Content $file.FullName -Raw -Encoding UTF8
    $text = Convert-HtmlToPlainText $html
    $text = Sanitize-ReportText $text

    return @"
===== $title =====
Source File: $($file.Name)

$text

"@
}

$pcReport = Get-LatestReportText "pc_status_report_*.html" "PC STATUS REPORT"
$networkReport = Get-LatestReportText "network_status_report_*.html" "NETWORK STATUS REPORT"
$folderReport = Get-LatestReportText "folder_radar_report_*.html" "FOLDER RADAR REPORT"
$lanReport = Get-LatestReportText "lan_scan_report_*.html" "LAN SCAN REPORT"

$prompt = @"
You are a PC health analysis assistant.

Below are local reports generated by my own PowerShell scripts, including PC status, network status, disk usage, and LAN scan reports.

The reports have been privacy-sanitized. Usernames, computer names, public IPs, exact local IPs, MAC addresses, SSIDs, and user directory paths may be replaced with placeholders such as <USER>, <COMPUTER>, <PUBLIC_IP>, <MAC_REDACTED>, <SSID_REDACTED>, or 192.168.x.x.

Please analyze them and reply in Simplified Chinese.

Please structure your answer as:

1. Overall health summary
2. Possible issues
3. Disk space suggestions
4. Memory and process suggestions
5. Network, DNS, and proxy suggestions
6. LAN device observations
7. Top 3 recommended actions

Rules:
- Do not suggest downloading unknown software.
- Do not suggest deleting system files casually.
- Do not suggest disabling security-related services casually.
- If the information is insufficient, say so clearly.
- Suggestions should be specific, practical, and low-risk.

$pcReport

$networkReport

$folderReport

$lanReport
"@

$prompt | Out-File -FilePath $output -Encoding utf8

Write-Host "AI review prompt generated:"
Write-Host $output

Start-Process notepad.exe $output